export declare const CREATE_PROCESS = 'CREATE_PROCESS';
export declare const READ_PROCESS = 'READ_PROCESS';
export declare const READ_PAGINATION_PROCESS = 'READ_PAGINATION_PROCESS';
export declare const READ_ENTIRE_PROCESS = 'READ_ENTIRE_PROCESS';
export declare const UPDATE_PARTIAL_PROCESS = 'UPDATE_PARTIAL_PROCESS';
export declare const UPDATE_BATCH_PROCESS = 'UPDATE_BATCH_PROCESS';
export declare const UPDATE_ENTIRE_PROCESS = 'UPDATE_ENTIRE_PROCESS';
export declare const UPDATE_ENTIRE_BATCH_PROCESS =
  'UPDATE_ENTIRE_BATCH_PROCESS';
export declare const DELETE_PROCESS = 'DELETE_PROCESS';
export declare const DELETE_BATCH_PROCESS = 'DELETE_BATCH_PROCESS';
